---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

defaultStrokeThresholds: &defaultStrokeThresholds 
  - {color: "stroke_low", level: 1}
  - {color: "stroke_medium", level: 10}
  - {color: "stroke_high", level: 25}

defaultFillThresholds: &defaultFillThresholds
  - {color: "fill_low", level: 1}
  - {color: "fill_medium", level: 10}
  - {color: "fill_high", level: 25}

defaultLabelThresholds: &defaultLabelThresholds
  - {color: "label_low", level: 1}
  - {color: "label_medium", level: 10}
  - {color: "label_high", level: 25}

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
datapoint: "last"
gradient: "none"

cells:
  tactic-TA0002:
    dataRef: falco-TA0002
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  border-TA0002:
    dataRef: falco-TA0002
    strokeColor:
      thresholds: *defaultStrokeThresholds
  technique-T1047:
    dataRef: falco-T1047
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1129:
    dataRef: falco-T1129
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1675:
    dataRef: falco-T1675
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1053:
    dataRef: falco-T1053
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1106:
    dataRef: falco-T1106
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1610:
    dataRef: falco-T1610
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1674:
    dataRef: falco-T1674
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1059:
    dataRef: falco-T1059
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1609:
    dataRef: falco-T1609
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1204:
    dataRef: falco-T1204
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1072:
    dataRef: falco-T1072
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1559:
    dataRef: falco-T1559
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1203:
    dataRef: falco-T1203
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1569:
    dataRef: falco-T1569
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1651:
    dataRef: falco-T1651
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1648:
    dataRef: falco-T1648
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
