---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

defaultStrokeThresholds: &defaultStrokeThresholds 
  - {color: "stroke_low", level: 1}
  - {color: "stroke_medium", level: 10}
  - {color: "stroke_high", level: 25}

defaultFillThresholds: &defaultFillThresholds
  - {color: "fill_low", level: 1}
  - {color: "fill_medium", level: 10}
  - {color: "fill_high", level: 25}

defaultLabelThresholds: &defaultLabelThresholds
  - {color: "label_low", level: 1}
  - {color: "label_medium", level: 10}
  - {color: "label_high", level: 25}

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
datapoint: "last"
gradient: "none"

cells:
  tactic-TA0003:
    dataRef: falco-TA0003
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  border-TA0003:
    dataRef: falco-TA0003
    strokeColor:
      thresholds: *defaultStrokeThresholds
  technique-T1037:
    dataRef: falco-T1037
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1543:
    dataRef: falco-T1543
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1133:
    dataRef: falco-T1133
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1547:
    dataRef: falco-T1547
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1137:
    dataRef: falco-T1137
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1053:
    dataRef: falco-T1053
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1176:
    dataRef: falco-T1176
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1205:
    dataRef: falco-T1205
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1525:
    dataRef: falco-T1525
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1112:
    dataRef: falco-T1112
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1542:
    dataRef: falco-T1542
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1554:
    dataRef: falco-T1554
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1098:
    dataRef: falco-T1098
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1574:
    dataRef: falco-T1574
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1078:
    dataRef: falco-T1078
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1546:
    dataRef: falco-T1546
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1671:
    dataRef: falco-T1671
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1197:
    dataRef: falco-T1197
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1505:
    dataRef: falco-T1505
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1668:
    dataRef: falco-T1668
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1136:
    dataRef: falco-T1136
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1653:
    dataRef: falco-T1653
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1556:
    dataRef: falco-T1556
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
