---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

defaultStrokeThresholds: &defaultStrokeThresholds 
  - {color: "stroke_low", level: 1}
  - {color: "stroke_medium", level: 10}
  - {color: "stroke_high", level: 25}

defaultFillThresholds: &defaultFillThresholds
  - {color: "fill_low", level: 1}
  - {color: "fill_medium", level: 10}
  - {color: "fill_high", level: 25}

defaultLabelThresholds: &defaultLabelThresholds
  - {color: "label_low", level: 1}
  - {color: "label_medium", level: 10}
  - {color: "label_high", level: 25}

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
datapoint: "last"
gradient: "none"

cells:
  tactic-TA0043-TA0042:
    dataRef: falco-TA0043-TA0042
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  border-TA0043-TA0042:
    dataRef: falco-TA0043-TA0042
    strokeColor:
      thresholds: *defaultStrokeThresholds
  technique-T1592:
    dataRef: falco-T1592
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1594:
    dataRef: falco-T1594
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1589:
    dataRef: falco-T1589
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1596:
    dataRef: falco-T1596
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1595:
    dataRef: falco-T1595
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1591:
    dataRef: falco-T1591
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1590:
    dataRef: falco-T1590
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1593:
    dataRef: falco-T1593
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1597:
    dataRef: falco-T1597
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1598:
    dataRef: falco-T1598
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1583:
    dataRef: falco-T1583
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1584:
    dataRef: falco-T1584
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1586:
    dataRef: falco-T1586
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1608:
    dataRef: falco-T1608
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1585:
    dataRef: falco-T1585
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1588:
    dataRef: falco-T1588
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1650:
    dataRef: falco-T1650
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1587:
    dataRef: falco-T1587
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
