---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

defaultStrokeThresholds: &defaultStrokeThresholds 
  - {color: "stroke_low", level: 1}
  - {color: "stroke_medium", level: 50}
  - {color: "stroke_high", level: 100}

defaultFillThresholds: &defaultFillThresholds
  - {color: "fill_low", level: 1}
  - {color: "fill_medium", level: 50}
  - {color: "fill_high", level: 100}

defaultLabelThresholds: &defaultLabelThresholds
  - {color: "label_low", level: 1}
  - {color: "label_medium", level: 50}
  - {color: "label_high", level: 100}

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
datapoint: "last"
gradient: "none"

cells:
  tactic-TA0001:
    dataRef: falco-TA0001
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  border-TA0001:
    dataRef: falco-TA0001
    strokeColor:
      thresholds: *defaultStrokeThresholds
  technique-T1133:
    dataRef: falco-T1133
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1091:
    dataRef: falco-T1091
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1195:
    dataRef: falco-T1195
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1190:
    dataRef: falco-T1190
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1659:
    dataRef: falco-T1659
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1199:
    dataRef: falco-T1199
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1566:
    dataRef: falco-T1566
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1078:
    dataRef: falco-T1078
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1200:
    dataRef: falco-T1200
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1189:
    dataRef: falco-T1189
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1669:
    dataRef: falco-T1669
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
