---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

defaultStrokeThresholds: &defaultStrokeThresholds 
  - {color: "stroke_low", level: 1}
  - {color: "stroke_medium", level: 50}
  - {color: "stroke_high", level: 100}

defaultFillThresholds: &defaultFillThresholds
  - {color: "fill_low", level: 1}
  - {color: "fill_medium", level: 50}
  - {color: "fill_high", level: 100}

defaultLabelThresholds: &defaultLabelThresholds
  - {color: "label_low", level: 1}
  - {color: "label_medium", level: 50}
  - {color: "label_high", level: 100}

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
datapoint: "last"
gradient: "none"

cells:
  tactic-TA0008:
    dataRef: falco-TA0008
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  border-TA0008:
    dataRef: falco-TA0008
    strokeColor:
      thresholds: *defaultStrokeThresholds
  technique-T1080:
    dataRef: falco-T1080
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1091:
    dataRef: falco-T1091
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1550:
    dataRef: falco-T1550
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1021:
    dataRef: falco-T1021
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1563:
    dataRef: falco-T1563
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1072:
    dataRef: falco-T1072
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1210:
    dataRef: falco-T1210
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1534:
    dataRef: falco-T1534
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
  technique-T1570:
    dataRef: falco-T1570
    labelColor:
      thresholds: *defaultLabelThresholds
    strokeColor:
      thresholds: *defaultStrokeThresholds
    fillColor:
      thresholds: *defaultFillThresholds
