---

zoomPanPinch:
  wheelActivationKeys: ["Alt"]

colors:
  black: "#000000"
  cioccolato: "#55280C"
  frangipani: "#FFDEB3"
  gold: "#FFD700"
  pizazz: "#FF9000"
  red_ribbon: "#ED0A3F"
  saddle_brown_approx: "#4A3D00"
  temptress: "#3B000B"
  varden: "#FFF6DF"
  vivid_tangerine: "#FF9980"

cellColorMappings:
  darkTheme:
    # Low
    label_low: "gold"
    stroke_low: "gold"
    fill_low: "saddle_brown_approx"
    # Medium
    label_medium: "pizazz"
    stroke_medium: "pizazz"
    fill_medium: "cioccolato"
    # High
    label_high: "red_ribbon"
    stroke_high: "red_ribbon"
    fill_high: "temptress"
  lightTheme:
    # Low
    label_low: "black"
    stroke_low: "gold"
    fill_low: "varden"
    # Medium
    label_medium: "black"
    stroke_medium: "pizazz"
    fill_medium: "frangipani"
    # High
    label_high: "black"
    stroke_high: "red_ribbon"
    fill_high: "vivid_tangerine"
